# Generated by Django 6.1.1 on 2026-09-16 03:14

import django.core.validators
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique alphanumeric identifier (3-20 characters)', max_length=20, unique=True, validators=[portal.models.validate_employee_id, django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(20)])),
                ('first_name', models.CharField(help_text='First name (2-50 characters)', max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50)])),
                ('last_name', models.CharField(help_text='Last name (2-50 characters)', max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50)])),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Human Resources', 'Human Resources'), ('Finance', 'Finance'), ('Operations', 'Operations'), ('Information Technology', 'Information Technology'), ('Design', 'Design'), ('Customer Support', 'Customer Support'), ('Legal', 'Legal')], help_text='Department assignment', max_length=50)),
                ('employment_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('On Leave', 'On Leave')], default='Active', help_text='Current employment status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['employee_id'],
            },
        ),
    ]
